//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemGear.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemGear.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap AddButton {
            get {
                object obj = ResourceManager.GetObject("AddButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap AllSettings_256x256 {
            get {
                object obj = ResourceManager.GetObject("AllSettings_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap AllSettings_28x28 {
            get {
                object obj = ResourceManager.GetObject("AllSettings_28x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap AllSettings_32x24 {
            get {
                object obj = ResourceManager.GetObject("AllSettings_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap AllSettings_36x36 {
            get {
                object obj = ResourceManager.GetObject("AllSettings_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap AllSettings_72x72 {
            get {
                object obj = ResourceManager.GetObject("AllSettings_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BackBtn {
            get {
                object obj = ResourceManager.GetObject("BackBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BackupSettingsLogo_36x36 {
            get {
                object obj = ResourceManager.GetObject("BackupSettingsLogo_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BackupSettingsLogo_72x72 {
            get {
                object obj = ResourceManager.GetObject("BackupSettingsLogo_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BrowserMgr_32x24 {
            get {
                object obj = ResourceManager.GetObject("BrowserMgr_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BrowserMgr_36x36 {
            get {
                object obj = ResourceManager.GetObject("BrowserMgr_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BrowserMgr_72x72 {
            get {
                object obj = ResourceManager.GetObject("BrowserMgr_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ChangeSkin {
            get {
                object obj = ResourceManager.GetObject("ChangeSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Clipboard_72x72 {
            get {
                object obj = ResourceManager.GetObject("Clipboard_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemGear]
        ///Version=#3.0
        ///FileType=#CLSIDIcon_V1
        ///
        ///[maininfo]
        ///clsid=#{984147CC-CF59-492B-A7C6-F299762A9E51}
        ///name=#您的CLSID图标
        ///icon=#%resources%\images\res\clsidicon.ico
        ///count=#17
        ///[1]
        ///regname=#0000001
        ///name=#系统齿轮
        ///command=#%appexe%
        ///arg=#
        ///icon=#%appexe%,0
        ///runasadmin=#F
        ///[2]
        ///regname=#0000002
        ///name=#桌面便利贴
        ///command=#%apppath%\desktoplabela.exe
        ///arg=#
        ///icon=#%apppath%\desktoplabela.exe,0
        ///runasadmin=#F
        ///[3]
        ///regname=#0000004
        ///name=#%mycomputer_name%
        ///command=#%windir%\explorer.exe
        ///arg=#/e,::{20D04FE0- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string CLSIDIcon_public {
            get {
                return ResourceManager.GetString("CLSIDIcon_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemGear.exe [/F] [/M=Itmes] [/L=&lt;FileName&gt;] [/B] [/D] [/C /Folder=&quot;&lt;FolderPath&gt;&quot;] [/I &lt;/Show&gt;][/H] [/P=&lt;Package&gt; &lt;/Operate&gt;][/?] &lt;/FunctionCode&gt; &lt;/FunctionFirstIndex&gt; &lt;/FunctionSecondIndex&gt; [/Q=&lt;FunctionName&gt;]
        ///
        ////M   进入主界面的选项卡
        ////F    进入系统齿轮的各个功能
        ////L    加载配置文件
        ////B    内部的返回参数
        ////D    清除由系统齿轮产生的临时文件,清理完成后,转至主界面&lt;未启用&gt;
        ////C    系统齿轮剪切板功能
        ////I     创建系统齿轮的快捷方式图标
        ////P    解压压缩包(已移除)
        ////H    显示帮助
        ////?     显示帮助
        ////Q    打开附加功能&lt;开发中&gt;
        ///
        ////M=Items Items为主界面的一级选项卡与二级选项卡的索引(从1开始)集合,形式为:(一级选项卡索引,二级选项卡索引)
        ///                 一级选项卡索引  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string CommandArgs {
            get {
                return ResourceManager.GetString("CommandArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap CurrentVersion {
            get {
                object obj = ResourceManager.GetObject("CurrentVersion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [{000214A0-0000-0000-C000-000000000046}]
        ///Prop4=31,www.hao123.com
        ///Prop3=19,2
        ///[{A7AF692E-098D-4C08-A225-D433CA835ED0}]
        ///Prop5=3,0
        ///Prop9=19,0
        ///Prop6=3,1
        ///Prop2=65,2C0000000200000003000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD900000061010000F90300005C030000B7
        ///[InternetShortcut]
        ///URL=www.54itmi.com
        ///IDList=
        ///IconFile=%windir%\system32\ieframe.dll
        ///IconIndex=22
        ///[{9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3}]
        ///Prop12=19,2
        ///Prop5=8,Microsoft.Website.C92EE8B1.DBAE1E52 的本地化字符串。
        /// </summary>
        public static string DefaultWebSite {
            get {
                return ResourceManager.GetString("DefaultWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap DesktopLabel_32x32 {
            get {
                object obj = ResourceManager.GetObject("DesktopLabel_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap DesktopLabel_36x36 {
            get {
                object obj = ResourceManager.GetObject("DesktopLabel_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap DesktopLabel_72x72 {
            get {
                object obj = ResourceManager.GetObject("DesktopLabel_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap EditButton {
            get {
                object obj = ResourceManager.GetObject("EditButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap FileMgr_256x256 {
            get {
                object obj = ResourceManager.GetObject("FileMgr_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap FileMgr_32x24 {
            get {
                object obj = ResourceManager.GetObject("FileMgr_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap FileMgr_36x36 {
            get {
                object obj = ResourceManager.GetObject("FileMgr_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap FileMgr_72x72 {
            get {
                object obj = ResourceManager.GetObject("FileMgr_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap FunctionIsDesign {
            get {
                object obj = ResourceManager.GetObject("FunctionIsDesign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap GiveFeedbackbyEMAIL {
            get {
                object obj = ResourceManager.GetObject("GiveFeedbackbyEMAIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap GiveFeedbackbyFacebook {
            get {
                object obj = ResourceManager.GetObject("GiveFeedbackbyFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap GiveFeedbackbyQQ {
            get {
                object obj = ResourceManager.GetObject("GiveFeedbackbyQQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap GiveFeedbackbywebpage {
            get {
                object obj = ResourceManager.GetObject("GiveFeedbackbywebpage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Help_28x28 {
            get {
                object obj = ResourceManager.GetObject("Help_28x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Help_32x24 {
            get {
                object obj = ResourceManager.GetObject("Help_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Help_36x36 {
            get {
                object obj = ResourceManager.GetObject("Help_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Help_72x72 {
            get {
                object obj = ResourceManager.GetObject("Help_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap IconAndLinkMgr_32x24 {
            get {
                object obj = ResourceManager.GetObject("IconAndLinkMgr_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap IconAndLinkMgr_36x36 {
            get {
                object obj = ResourceManager.GetObject("IconAndLinkMgr_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap IconAndLinkMgr_72x72 {
            get {
                object obj = ResourceManager.GetObject("IconAndLinkMgr_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap IELogo_36x36 {
            get {
                object obj = ResourceManager.GetObject("IELogo_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap IELogo_72x72 {
            get {
                object obj = ResourceManager.GetObject("IELogo_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Info_72x72 {
            get {
                object obj = ResourceManager.GetObject("Info_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap IT迷38X38 {
            get {
                object obj = ResourceManager.GetObject("IT迷38X38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Like_28x28 {
            get {
                object obj = ResourceManager.GetObject("Like_28x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Like_32x24 {
            get {
                object obj = ResourceManager.GetObject("Like_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Like_36x36 {
            get {
                object obj = ResourceManager.GetObject("Like_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Like_72x72 {
            get {
                object obj = ResourceManager.GetObject("Like_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap LOCK {
            get {
                object obj = ResourceManager.GetObject("LOCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap LockScreen_36x36 {
            get {
                object obj = ResourceManager.GetObject("LockScreen_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap LockScreen_72x72 {
            get {
                object obj = ResourceManager.GetObject("LockScreen_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap LOGO_ChooseDisk {
            get {
                object obj = ResourceManager.GetObject("LOGO_ChooseDisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap LOGOFF {
            get {
                object obj = ResourceManager.GetObject("LOGOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Menu_white {
            get {
                object obj = ResourceManager.GetObject("Menu_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Message_Error {
            get {
                object obj = ResourceManager.GetObject("Message_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Message_OK {
            get {
                object obj = ResourceManager.GetObject("Message_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Message_Question {
            get {
                object obj = ResourceManager.GetObject("Message_Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap MiniSize_White {
            get {
                object obj = ResourceManager.GetObject("MiniSize_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap NextBtn {
            get {
                object obj = ResourceManager.GetObject("NextBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap POWEROFF {
            get {
                object obj = ResourceManager.GetObject("POWEROFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ProgressBar_Wait {
            get {
                object obj = ResourceManager.GetObject("ProgressBar_Wait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Recover {
            get {
                object obj = ResourceManager.GetObject("Recover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap RefexonLogo {
            get {
                object obj = ResourceManager.GetObject("RefexonLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap RefexonLogo_36x36 {
            get {
                object obj = ResourceManager.GetObject("RefexonLogo_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap RESTART {
            get {
                object obj = ResourceManager.GetObject("RESTART", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap RightMenu {
            get {
                object obj = ResourceManager.GetObject("RightMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemGear]
        ///FileType=#RightMenuGroup
        ///Version=#3.0
        ///
        ///[MainInfo]
        ///Name=#上网必备工具
        ///RegName=#SG.RMG.Internet
        ///Icon=#%resources%\images\res\002.ico
        ///CommandCount=#5
        ///Position=#Top
        ///
        ///[Command1]
        ///RegName=#SG.RMG.Internet.SG
        ///Name=#系统齿轮
        ///Icon=#%appexe%,0
        ///Command=#&quot;%appexe%&quot;
        ///RunAsAdmin=#F
        ///IsFenGeFu=#F
        ///
        ///[Command2]
        ///RegName=#SG.RMG.Internet.Http
        ///Name=#%defaultbrowser_name%
        ///Icon=#%defaultbrowser_exe%,0
        ///Command=#&quot;%defaultbrowser_exe%&quot;
        ///RunAsAdmin=#F
        ///IsFenGeFu=#F
        ///
        ///[Command3]
        ///RegName=#SG.RMG.Internet.QQ
        ///Na [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RightMenuGroup_internet {
            get {
                return ResourceManager.GetString("RightMenuGroup_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemGear]
        ///FileType=#RightMenuGroup
        ///Version=#3.0
        ///
        ///[MainInfo]
        ///Name=#系统齿轮右键菜单组
        ///RegName=#SystemGear.Internet
        ///Icon=#%resources%\images\res\002.ico
        ///CommandCount=#0
        ///Position=#Top
        ///
        ///[Command1]
        ///RegName=#SystemGear.SystemGear
        ///Name=#系统齿轮
        ///Icon=#%appexe%,0
        ///Command=#%appexe%
        ///RunAsAdmin=#T
        ///IsFenGeFu=#F
        ///
        ///[Command2]
        ///RegName=#SystemGear.Http
        ///Name=#%defaultbrowser_name%
        ///Icon=#%defaultbrowser_exe%,0
        ///Command=#%defaultbrowser_exe%
        ///RunAsAdmin=#F
        ///IsFenGeFu=#F
        ///
        ///[Command3]
        ///RegName=#SystemGear.QQ
        ///Name=# [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RightMenuGroup_media {
            get {
                return ResourceManager.GetString("RightMenuGroup_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemGear]
        ///FileType=#RightMenuGroup
        ///Version=#3.0
        ///
        ///[MainInfo]
        ///Name=#电源管理组
        ///RegName=#电源管组
        ///Icon=#%resources%\images\res\002.ico
        ///CommandCount=#8
        ///Position=#
        ///
        ///[Command1]
        ///RegName=#SGMENU.CLOSESCREEN
        ///Name=#一键关屏
        ///Icon=#
        ///Command=#%apppath%\sgsheller.exe /s-&quot;closescreen&quot;
        ///RunAsAdmin=#F
        ///IsFenGeFu=#F
        ///
        ///[Command2]
        ///RegName=#
        ///Name=#
        ///Icon=#
        ///Command=#
        ///RunAsAdmin=#
        ///IsFenGeFu=#T
        ///
        ///[Command3]
        ///RegName=#SGMENU.POWEROFF
        ///Name=#关闭计算机
        ///Icon=#%resources%\Images\PowerMgrIcons\DKMGR_poweroff.ico
        ///Command=#%wind [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RightMenuGroup_powermgr {
            get {
                return ResourceManager.GetString("RightMenuGroup_powermgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemGear]
        ///FileType=#RightMenuGroup
        ///Version=#3.0
        ///
        ///[MainInfo]
        ///Name=#系统齿轮右键菜单组
        ///RegName=#SystemGear.Internet
        ///Icon=#%resources%\images\res\002.ico
        ///CommandCount=#0
        ///Position=#Top
        ///
        ///[Command1]
        ///RegName=#SystemGear.SystemGear
        ///Name=#系统齿轮
        ///Icon=#%appexe%,0
        ///Command=#%appexe%
        ///RunAsAdmin=#T
        ///IsFenGeFu=#F
        ///
        ///[Command2]
        ///RegName=#SystemGear.Http
        ///Name=#%defaultbrowser_name%
        ///Icon=#%defaultbrowser_exe%,0
        ///Command=#%defaultbrowser_exe%
        ///RunAsAdmin=#F
        ///IsFenGeFu=#F
        ///
        ///[Command3]
        ///RegName=#SystemGear.QQ
        ///Name=# [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RightMenuGroup_pro {
            get {
                return ResourceManager.GetString("RightMenuGroup_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemGear]
        ///FileType=#RightMenuGroup
        ///Version=#3.0
        ///
        ///[MainInfo]
        ///Name=#系统齿轮右键菜单组
        ///RegName=#系统齿轮右键菜单组
        ///Icon=#%resources%\images\res\002.ico
        ///CommandCount=#14
        ///Position=#Top
        ///
        ///[Command1]
        ///RegName=#SG.RMG.Public.SG
        ///Name=#系统齿轮
        ///Icon=#%appexe%,0
        ///Command=#&quot;%appexe%&quot;
        ///RunAsAdmin=#F
        ///IsFenGeFu=#F
        ///
        ///[Command2]
        ///RegName=#SG.RMG.Public.DesktopLabel
        ///Name=#桌面便利贴
        ///Icon=#%apppath%\desktoplabela.exe,0
        ///Command=#&quot;%apppath%\desktoplabela.exe&quot;
        ///RunAsAdmin=#F
        ///IsFenGeFu=#F
        ///
        ///
        ///[Command3]
        ///RegName=#SG.RMG.Public.Http
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RightMenuGroup_public {
            get {
                return ResourceManager.GetString("RightMenuGroup_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SystemGear]
        ///FileType=#RightMenuGroup
        ///Version=#3.0
        ///
        ///[MainInfo]
        ///Name=#Win8 自带工具
        ///RegName=#SG.RMG.WIN8
        ///Icon=#%resources%\images\res\002.ico
        ///CommandCount=#15
        ///Position=#Top
        ///
        ///[Command1]
        ///RegName=#SG.RMG.WIN8.PCSetting
        ///Name=#电脑设置
        ///Icon=#%Resources%\Images\WinAppLogo\controlpanel.ico
        ///Command=#%windir%\explorer.exe shell:::{4234d49b-0245-4df3-b780-3893943456e1}\windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel
        ///RunAsAdmin=#F
        ///IsFenGeFu=#F
        ///
        ///[Command2]
        ///RegName=#SG.RMG. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RightMenuGroup_win8 {
            get {
                return ResourceManager.GetString("RightMenuGroup_win8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap RightMenusMgr_32x24 {
            get {
                object obj = ResourceManager.GetObject("RightMenusMgr_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap RightMenusMgr_36x36 {
            get {
                object obj = ResourceManager.GetObject("RightMenusMgr_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap RightMenusMgr_72x72 {
            get {
                object obj = ResourceManager.GetObject("RightMenusMgr_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;以管理员身份运行程序的命令admin.vbs 
        ///Set objArgs = WScript. Arguments
        ///Set objWMIServices = GetObject(&quot;winmgmts:{impersonationLevel=impersonate}!\\.\root\cimv2&quot;) 
        ///Set objWbemObjectSet = objWMIServices.ExecQuery(_ 
        ///&quot;SELECT * FROM Win32_Process WHERE &quot; &amp;_ 
        ///&quot;ExecutablePath=&apos;&quot; &amp; Replace(WScript.FullName,&quot;\&quot;,&quot;\\&quot;) &amp; &quot;&apos; and &quot; &amp; _ 
        ///&quot;CommandLine LIKE &apos;%&quot; &amp; WScript.ScriptName &amp; &quot;%&apos;&quot;) 
        ///for each objWbemObject in objWbemObjectSet 
        ///cmdline = objWbemObject.CommandLine 
        ///path=CreateObject(&quot;WScript.Shell&quot;).CurrentDirectory &apos;的值是 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Select_Expand_Main {
            get {
                object obj = ResourceManager.GetObject("Select_Expand_Main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SelectFolderAndFiles {
            get {
                object obj = ResourceManager.GetObject("SelectFolderAndFiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SelectFunctionBox {
            get {
                object obj = ResourceManager.GetObject("SelectFunctionBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SendMEeQQMessange {
            get {
                object obj = ResourceManager.GetObject("SendMEeQQMessange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Settings_28x28 {
            get {
                object obj = ResourceManager.GetObject("Settings_28x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Settings_32x24 {
            get {
                object obj = ResourceManager.GetObject("Settings_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Settings_36x36 {
            get {
                object obj = ResourceManager.GetObject("Settings_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Settings_72x72 {
            get {
                object obj = ResourceManager.GetObject("Settings_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SG3Logo_30x30 {
            get {
                object obj = ResourceManager.GetObject("SG3Logo_30x30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SG3Logo_96x96 {
            get {
                object obj = ResourceManager.GetObject("SG3Logo_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SkinSelected {
            get {
                object obj = ResourceManager.GetObject("SkinSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SubCommands {
            get {
                object obj = ResourceManager.GetObject("SubCommands", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SystemBoot_32x24 {
            get {
                object obj = ResourceManager.GetObject("SystemBoot_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SystemBoot_36x36 {
            get {
                object obj = ResourceManager.GetObject("SystemBoot_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SystemBoot_72x72 {
            get {
                object obj = ResourceManager.GetObject("SystemBoot_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SystemDialog_32x24 {
            get {
                object obj = ResourceManager.GetObject("SystemDialog_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SystemDialog_36x36 {
            get {
                object obj = ResourceManager.GetObject("SystemDialog_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SystemDialog_72x72 {
            get {
                object obj = ResourceManager.GetObject("SystemDialog_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap TaskBar_Logo {
            get {
                object obj = ResourceManager.GetObject("TaskBar_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ToDoTip_1 {
            get {
                object obj = ResourceManager.GetObject("ToDoTip_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ToDoTip_2 {
            get {
                object obj = ResourceManager.GetObject("ToDoTip_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ToDoTip_3 {
            get {
                object obj = ResourceManager.GetObject("ToDoTip_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ToDoTip_4 {
            get {
                object obj = ResourceManager.GetObject("ToDoTip_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ToDoTip_5 {
            get {
                object obj = ResourceManager.GetObject("ToDoTip_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap UpdateDetail {
            get {
                object obj = ResourceManager.GetObject("UpdateDetail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap UpdateFileSize {
            get {
                object obj = ResourceManager.GetObject("UpdateFileSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap UpdateVersion {
            get {
                object obj = ResourceManager.GetObject("UpdateVersion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Warring {
            get {
                object obj = ResourceManager.GetObject("Warring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 V2.4 正式版 更新时间：2014-02-14 Build 2.4.0.1003
        ///+优化内部代码,合并多个函数
        ///+更改主界面布局
        ///+加入了深色主题
        ///+将&quot;文件夹美化&quot;更改为&quot;文件管理&quot;
        ///+加入了&quot;文件分拣&quot;功能
        ///+删除部分内嵌的资源文件
        ///+使用了多线程技术,提高程序的运行速度
        ///+解决了剪切板保存为文件的文件名的设置
        ///+解决了剪切板保存为文件路径为磁盘根目录时,无法保存文件的Bug
        ///+使用了窗体双缓存技术,解决部分控件图像闪烁的问题
        ///+解决了直接启动&quot;扩展名管理&quot;时,无法立即显示的问题
        ///+更改&quot;扩展名管理&quot;中文件类型的显示
        ///+加入了&quot;桌面图标&quot;主界面磁贴能获取桌面背景
        ///+加入了&quot;文件操作&quot;通用对话框
        ///+解决了&quot;右键菜单组&quot;名称的问题
        ///+加入了选择图标中默认的图标
        ///+优化部分图标以及文字显示
        ///+删除了&quot;桌面便利贴&quot;和&quot;挂机锁屏助手&quot;组件
        ///+解决了输入文字对话框部分显示的效果
        ///+更新了&quot;选择图标&quot;对话框布局并使用了默认图标选项
        ///+增加了开始屏幕设置对Windows 8.1的支持
        ///+修改了&quot;任务栏图标&quot;的部分功能以及界面的调整
        ///+加入了&quot;其他美化&quot;、&quot;系统窗口&quot;和&quot;Wi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string WhatIsNew {
            get {
                return ResourceManager.GetString("WhatIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win_XMenu_72x72 {
            get {
                object obj = ResourceManager.GetObject("Win_XMenu_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB01 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB02 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB03 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB04 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB05 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB06 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB07 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB08 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB09 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB10 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB11 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB12 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB13 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB14 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB15 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB16 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB17 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB18 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIN81STB19 {
            get {
                object obj = ResourceManager.GetObject("WIN81STB19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_1 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_10 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_11 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_12 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_13 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_14 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_15 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_16 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_17 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_18 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_19 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_2 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_20 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_3 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_4 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_5 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_6 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_7 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_8 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Back_9 {
            get {
                object obj = ResourceManager.GetObject("Win8Back_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap win8sc_choose {
            get {
                object obj = ResourceManager.GetObject("win8sc_choose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Style_32x24 {
            get {
                object obj = ResourceManager.GetObject("Win8Style_32x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Style_36x36 {
            get {
                object obj = ResourceManager.GetObject("Win8Style_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Win8Style_72x72 {
            get {
                object obj = ResourceManager.GetObject("Win8Style_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WinXMenus {
            get {
                object obj = ResourceManager.GetObject("WinXMenus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 选择滑块 {
            get {
                object obj = ResourceManager.GetObject("选择滑块", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
