using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace SystemGear.窗体
{
    public partial class SGForm_WIN10STYLE : Form
    {
        public SGForm_WIN10STYLE()
        {
            InitializeComponent();
        }

        private void myNormalButton1_Click(object sender, EventArgs e)
        {

        }

        private void tableLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
